# Generated by Django 3.0.7 on 2020-07-07 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='name_of_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='post_date_review',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_of_ad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='advertisments.Ad'),
        ),
    ]
