# Generated by Django 3.0.7 on 2020-07-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisments', '0006_contact_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reply',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
