# Generated by Django 3.0.7 on 2020-07-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisments', '0007_auto_20200713_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='post_date_contact',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
