# Generated by Django 3.0.7 on 2020-07-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisments', '0008_contact_post_date_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reply',
            field=models.CharField(default='', max_length=200),
        ),
    ]
