# Generated by Django 3.0.7 on 2020-07-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisments', '0009_auto_20200713_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='No Reply', max_length=200),
        ),
    ]
