# Generated by Django 3.0.7 on 2020-07-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisments', '0010_auto_20200713_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reply',
            field=models.CharField(default='No Reply', max_length=200),
        ),
    ]
